import { ImportStats,ProcessedContact,RawContactInput } from './types'; import { normalizeIndianPhone } from './phone-normalizer';
export function processAndDeduplicate(rawInputs:RawContactInput[]):{processedContacts:ProcessedContact[];stats:ImportStats;duplicateGroups:{canonicalPhone:string;chosenContact:ProcessedContact;allRowIndices:number[]}[]} {
 const mapped=rawInputs.map((r)=>{const n=normalizeIndianPhone(r.originalPhone); const c:ProcessedContact={id:`contact-${r.originalRowIndex}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,originalRowIndex:r.originalRowIndex,originalName:r.originalName,originalPhone:r.originalPhone,normalizedCanonical:n.canonicalPhone,googleInternationalPhone:n.googlePhone,finalName:r.originalName.trim()||n.canonicalPhone||r.originalPhone||`Contact #${r.originalRowIndex}`,status:n.isValid?'valid':n.statusCode==='NEEDS_REVIEW'?'needs_review':'invalid',validationMessage:n.validationMessage,isDuplicate:false,isSelected:n.isValid}; return c;});
 const groups=new Map<string,ProcessedContact[]>(), invalid:ProcessedContact[]=[]; mapped.forEach(c=>{if(!c.normalizedCanonical) invalid.push(c); else groups.set(c.normalizedCanonical,[...(groups.get(c.normalizedCanonical)||[]),c]);});
 const out:ProcessedContact[]=[], duplicateGroups:{canonicalPhone:string;chosenContact:ProcessedContact;allRowIndices:number[]}[]=[]; let duplicatesRemoved=0;
 groups.forEach((group,canonical)=>{if(group.length===1){out.push(group[0]);return;} const best=group.find(c=>c.originalName.trim()&&c.originalName.trim()!==canonical)||group[0]; const rows=group.map(c=>c.originalRowIndex); const chosen={...best,isDuplicate:false,duplicateOriginalRows:rows}; out.push(chosen); duplicateGroups.push({canonicalPhone:canonical,chosenContact:chosen,allRowIndices:rows}); group.filter(c=>c.id!==best.id).forEach(d=>out.push({...d,status:'duplicate',isDuplicate:true,isSelected:false,validationMessage:`Duplicate of Row #${best.originalRowIndex} (${canonical})`})); duplicatesRemoved+=group.length-1;});
 const processedContacts=[...out,...invalid].sort((a,b)=>a.originalRowIndex-b.originalRowIndex); const validContacts=processedContacts.filter(c=>c.status==='valid'&&!c.isDuplicate).length; const invalidContacts=processedContacts.filter(c=>(c.status==='invalid'||c.status==='needs_review')&&!c.isDuplicate).length;
 return {processedContacts,stats:{totalImportedRows:rawInputs.length,validContacts,invalidContacts,duplicatesRemoved,readyToSave:validContacts},duplicateGroups};
}
